### PR TITLE
Use powershell script to send alert on Windows

### PR DESCRIPTION
**Pull request by jebej**
That way the Python dependency can be removed.

### CODE REVIEW

**Comment by jebej** [comment]
Seems to work fine on my computer. I believe that powershell should always be on the path.

**Comment by haberdashPI** [comment]
I looked into powershell, the issue I had was that to run such a script you have to enable an option in your settings for it to properly run. I wanted a solution that didn't require any configuration during install. If I'm wrong about that please correct me!

**Comment by haberdashPI** [comment]
Just tried your PR out on my machine and it seemed to work... I guess I'm wrong about the permissions issue. I'm still a bit nervous. I'm pretty new to a Windows environment (I use MacOS primarily): can you explain why [this document](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7) doesn't apply?

**Comment by jebej** [comment]
I am not certain, maybe other people should try it to ensure it works for everyone.

**Comment by haberdashPI** [comment]
I've now [looked into this](https://blog.netspi.com/15-ways-to-bypass-the-powershell-execution-policy/). It looks like your solution should work across systems because you pass the script as an argument, rather than running it as file (which bypasses the execution policy).

**Comment by jebej** [comment]
Ah I thought that might be the case. Seems like a security bug though. As long as it doesn’t get fixed this will work...

**Comment by haberdashPI** [comment]
From my reading in that blog post, the execution policy is not really intended to be a security feature so much as a sanity feature, and there are literally at least 14 other workarounds that can be used, if that one happens to be "fixed".

**Pull request merged**
